### ISSUE TITLE
bs

### ISSUE THREAD

**Issue by aocyz** [SudoSuu/SnapchatUsernameChecker#3]
...

**Comment by redmonmd** [comment]
1. Install python off of the official link [python download link](python.org)
2. Click on and open that executable file to install python
3. Open a terminal or CMD prompt at the location where you downloaded this project
4. type in 
```
python3 snapchat.py
```

Hope this helps! 😁

**Comment by SudoSuu** [comment]
Thanks

**Comment by 080S** [comment]
> .
==============
Just because you have no clue on how to run a simple script dont go around calling bs or a language shit
